UPDATE WebMetric SET project = "aerogear" WHERE site ="jboss.org" and page like"%/aerogear%"and project = "jboss.org";
UPDATE WebMetric SET project = "apiviz" WHERE site ="jboss.org" and page like"%/apiviz%"and project = "jboss.org";
UPDATE WebMetric SET project = "arquillian" WHERE site ="jboss.org" and page like"%/arquillian%"and project = "jboss.org";
UPDATE WebMetric SET project = "blacktie" WHERE site ="jboss.org" and page like"%/blacktie%"and project = "jboss.org";
UPDATE WebMetric SET project = "boxgrinder" WHERE site ="jboss.org" and page like"%/boxgrinder%"and project = "jboss.org";
UPDATE WebMetric SET project = "byteman" WHERE site ="jboss.org" and page like"%/byteman%"and project = "jboss.org";
UPDATE WebMetric SET project = "capedwarf" WHERE site ="jboss.org" and page like"%/capedwarf%"and project = "jboss.org";
UPDATE WebMetric SET project = "cirras" WHERE site ="jboss.org" and page like"%/cirras%"and project = "jboss.org";
UPDATE WebMetric SET project = "drools" WHERE site ="jboss.org" and page like"%/drools%"and project = "jboss.org";
UPDATE WebMetric SET project = "ejb" WHERE site ="jboss.org" and page like"%/ejb3%"and project = "jboss.org";
UPDATE WebMetric SET project = "errai" WHERE site ="jboss.org" and page like"%/errai%"and project = "jboss.org";
UPDATE WebMetric SET project = "forge" WHERE site ="jboss.org" and page like"%/forge%"and project = "jboss.org";
UPDATE WebMetric SET project = "gatein" WHERE site ="jboss.org" and page like"%/gatein%"and project = "jboss.org";
UPDATE WebMetric SET project = "guvnor" WHERE site ="jboss.org" and page like"%/guvnor%"and project = "jboss.org";
UPDATE WebMetric SET project = "hibernate" WHERE site ="jboss.org" and page like"%/hibernate%"and project = "jboss.org";
UPDATE WebMetric SET project = "hornetq" WHERE site ="jboss.org" and page like"%/hornetq%"and project = "jboss.org";
UPDATE WebMetric SET project = "immutant" WHERE site ="jboss.org" and page like"%/immutant%"and project = "jboss.org";
UPDATE WebMetric SET project = "infinispan" WHERE site ="jboss.org" and page like"%/infinispan%"and project = "jboss.org";
UPDATE WebMetric SET project = "jbossas" WHERE site ="jboss.org" and page like"%/jbossapplicationserver7%"and project = "jboss.org";
UPDATE WebMetric SET project = "jbossesb" WHERE site ="jboss.org" and page like"%/jbossesb%"and project = "jboss.org";
UPDATE WebMetric SET project = "jbossweb" WHERE site ="jboss.org" and page like"%/jbossweb%"and project = "jboss.org";
UPDATE WebMetric SET project = "jBPM" WHERE site ="jboss.org" and page like"%/jbpm%"and project = "jboss.org";
UPDATE WebMetric SET project = "keycloak" WHERE site ="jboss.org" and page like"%/keycloak%"and project = "jboss.org";
UPDATE WebMetric SET project = "narayana" WHERE site ="jboss.org" and page like"%/narayana%"and project = "jboss.org";
UPDATE WebMetric SET project = "optaplanner" WHERE site ="jboss.org" and page like"%/optaplanner%"and project = "jboss.org";
UPDATE WebMetric SET project = "osgi" WHERE site ="jboss.org" and page like"%/osgi%"and project = "jboss.org";
UPDATE WebMetric SET project = "picketbox" WHERE site ="jboss.org" and page like"%/picketbox%"and project = "jboss.org";
UPDATE WebMetric SET project = "picketlink" WHERE site ="jboss.org" and page like"%/picketlink%"and project = "jboss.org";
UPDATE WebMetric SET project = "resteasy" WHERE site ="jboss.org" and page like"%/resteasy%"and project = "jboss.org";
UPDATE WebMetric SET project = "richfaces" WHERE site ="jboss.org" and page like"%/richfaces%"and project = "jboss.org";
UPDATE WebMetric SET project = "seam" WHERE site ="jboss.org" and page like"%/seam%"and project = "jboss.org";
UPDATE WebMetric SET project = "snowdrop" WHERE site ="jboss.org" and page like"%/snowdrop%"and project = "jboss.org";
UPDATE WebMetric SET project = "stormgrind" WHERE site ="jboss.org" and page like"%/stormgrind%"and project = "jboss.org";
UPDATE WebMetric SET project = "switchyard" WHERE site ="jboss.org" and page like"%/switchyard%"and project = "jboss.org";
UPDATE WebMetric SET project = "teiid" WHERE site ="jboss.org" and page like"%/teiid%"and project = "jboss.org";
UPDATE WebMetric SET project = "jbosstools" WHERE site ="jboss.org" and page like"%/jbosstools%"and project = "jboss.org";
UPDATE WebMetric SET project = "torquebox" WHERE site ="jboss.org" and page like"%/torquebox%"and project = "jboss.org";
UPDATE WebMetric SET project = "weld" WHERE site ="jboss.org" and page like"%/weld%"and project = "jboss.org";
UPDATE WebMetric SET project = "wildfly" WHERE site ="jboss.org" and page like"%/wildflyapplicationserver%"and project = "jboss.org";
UPDATE WebMetric SET project = "windup" WHERE site ="jboss.org" and page like"%/windup%"and project = "jboss.org";
UPDATE WebMetric SET project = "jbossws" WHERE site ="jboss.org" and page like"/jbossws%" and project = "jboss.org";
UPDATE WebMetric SET project = "microcontainer" WHERE site ="jboss.org" and page like"/jbossmc%" and project = "jboss.org";
UPDATE WebMetric SET project = "jbosstools" WHERE site ="jboss.org" and page like"/jbosside%" and project = "jboss.org";
UPDATE WebMetric SET project = "jbossas" WHERE site ="jboss.org" and page like"/jbossas%"and project = "jboss.org";
UPDATE WebMetric SET project = "JBossWay" WHERE site ="jboss.org" and page like"/developer%"and project = "jboss.org";
UPDATE WebMetric SET project = "riftsaw" WHERE site ="jboss.org" and page like"/riftsaw%" and project = "jboss.org";
update WebMetric set project = "EAP" where page like "/products/eap%" and site="www.jboss.org";
update WebMetric set project = "EWS" where page like "/products/eap%" and project="jboss.org";
update WebMetric set project = "FSW" where page like "/products/fsw%" and project="jboss.org";
update WebMetric set project = "JBDS" where page like "/products/jbds%" and project="jboss.org";
update WebMetric set project = "JDG" where page like "/products/jdg%" and project="jboss.org";
update WebMetric set project = "JPP" where page like "/products/jpp%" and project="jboss.org";
update WebMetric set project = "FUSE" where page like "/products/fuse%" and project="jboss.org";
update WebMetric set project = "BPMS" where page like "/products/bpmsuite%" and project="jboss.org";
update WebMetric set project = "BRMS" where page like "/products/brms%" and project="jboss.org";
